services: 
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ranish
      - MYSQL_USER=ranish 
      - MYSQL_PASSWORD=ranish
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root  
      - PMA_PASSWORD=ranish